return {
	Name = "A-1 Cucumber Gun",
	Category = "Gun",
	Weight = "Moderate",
	Price = 1000000,
	Level = 70,
	Lore = "Invented by a finnish scientist on a weekend. Not consumable. Eating results in fines.",
	SpecialText = "Huge recoil, nuclear damage",
	GroupUnlocked = true,
	Consumable = false,
	GamepassId = 0,
	PreviewImage = "rbxassetid://112682743067865",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -2),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "EXPLOSIVE", Color = Color3.new(1, 0, 0) },
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
