return {
	Name = "AK47",
	Category = "Gun",
	Weight = "Moderate",
	Price = 8000,
	Level = 5,
	Lore = "Stolen from a CS-GO player. Please don't tell them. They're not happy about it.",
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://72190454377960",

	PreviewCameraOffset = Vector3.new(0, 0, 1),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {},
}
