return {
	Name = "Banana Gun",
	Category = "Gun",
	Weight = "Light",
	Price = 35000,
	Level = 25,
	Lore = "Stolen from a produce section. Found out to be extremely radioactive. Do not eat.",
	SpecialText = "Infinite clip, small knockback enables weak flight.",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://135314691401790",

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "INFINITE", Color = Color3.new(1, 1, 0) },
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
