return {
	Name = "Combat Shotgun",
	Category = "Gun",
	Weight = "Moderate",
	Price = 15000,
	Level = 20,
	Lore = "A reliable close-range weapon. Great for close range encounters.",
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://97773284592249",

	PreviewModelOrientationOffset = Vector3.new(0, 0, -1),
	PreviewCameraOffset = Vector3.new(0, 0, -6),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
