return {
	Name = "Heavy Cannon",
	Category = "Gun",
	Weight = "Moderate",
	Price = 35000,
	Level = 5,
	Lore = "A heavy hitting automatic weapon for delivering decent rapid fire damage.",
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://139414116860988",

	PreviewCameraOffset = Vector3.new(0, 0, -5),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {},
}
