return {
	Name = "Infinite Revolver",
	Category = "Gun",
	Weight = "Light",
	Price = 45000,
	Level = 50,
	Lore = "Only weapon in the world with a felony. Breaks Newton's law of motion.",
	SpecialText = "Infinite clip. Don't ask me how. I didn't make it.",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://115096989359910",

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "INFINITE", Color = Color3.new(1, 1, 0) },
	},
}
