return {
	Name = "Hyperlaser Gun",
	Category = "Gun",
	Weight = "Light",
	Price = 0,
	Level = 0,
	Lore = "Found under a UFO. Scientists believe this is the future of weaponry. Others are eating toasters.",
	SpecialText = "Vaporizes on kill",
	GroupUnlocked = true,
	GroupId = 17170194,
	Consumable = false,

	PreviewImage = "rbxassetid://124793212757753",

	ItemInfo = {
		DamageType = "Special",
	},

	Pills = {
		{ Text = "GROUP", Color = Color3.new(1, 0, 0.0156863) },
		{ Text = "VAPORIZES", Color = Color3.new(0, 0.682353, 1) },
	},
}
