return {
	Name = "linus",
	Category = "Gun",
	Weight = "Moderate",
	Price = 66666,
	Level = 15,
	Lore = "Apparently belongs to the CEO. Eats the souls of the damned. ",
	SpecialText = "Trivia: Originally an admin gun until Morse released it. Caused the death of the mayor.",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://73748517872084",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -3),

	ItemInfo = {
		DamageType = "Special",
	},

	Pills = {
		{ Text = "MAGICAL", Color = Color3.new(0.8, 0, 0.6) },
		{ Text = "DARK ENERGY", Color = Color3.new(0.3, 0, 0.6) },
	},
}
