return {
	Name = "M4A1",
	Category = "Gun",
	Weight = "Moderate",
	Price = 10000,
	Level = 0,
	Lore = 'The true OG of the automatic weapons. Please send an "Amen"',
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://135678735388202",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -5),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {},
}
