return {
	Name = "Minigun",
	Category = "Gun",
	Weight = "Heavy",
	Price = 600000,
	Level = 60,
	Lore = "I am heavy weapons guy, and this is my weapon.",
	SpecialText = "Unable to sprint while active",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://126113456551510",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -3),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {},
}
