return {
	Name = "Morseconsin 1834",
	Category = "Gun",
	Weight = "Moderate",
	Price = 77000,
	Level = 40,
	Lore = "The founder's own sniper rifle. Sponsored by the mayor. Was. Until he died.",
	SpecialText = "Penetrates targets, has scope",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://111531264857662",

	ItemInfo = {
		DamageType = "Bullet",
	},

	PreviewCameraOffset = Vector3.new(0, 0, -5),

	Pills = {
		{ Text = "SCOPE", Color = Color3.new(0.607843, 0.607843, 0.607843) },
		{ Text = "PENETRATING", Color = Color3.new(1, 0, 0) },
	},
}
