return {
	Name = "Nuke Launcher",
	Category = "Gun",
	Weight = "Heavy",
	Price = 0,
	Level = 0,
	Lore = "From the Military Base. Destroys everything in its radius. Do not bring to the airport",
	SpecialText = "Illegal in Wisconsin due to stench. Please don't use it there.",
	GroupUnlocked = true,
	Consumable = false,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://76392078008669",
	BadgeTag = "Nuke",
	ItemInfo = {
		DamageType = "Bullet",
	},

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -7),

	Pills = {
		{ Text = "EXPLOSIVE", Color = Color3.new(1, 0, 0) },
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
