return {
	Name = "RPG",
	Category = "Gun",
	Weight = "Heavy",
	Price = 50000,
	Level = 60,
	Lore = "Explodes things. Really good. Endorsed by Rhode Island.",
	SpecialText = "Launches targets and explodes them.",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://118166109722664",

	ItemInfo = {
		DamageType = "Special",
	},

	PreviewCameraOffset = Vector3.new(0, 0, -8),

	Pills = {
		{ Text = "EXPLOSIVE", Color = Color3.new(1, 0, 0) },
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
