return {
	Name = "Spas-12",
	Category = "Gun",
	Weight = "Moderate",
	Price = 5000,
	Level = 30,
	Lore = "A decently powerful shotgun.",
	SpecialText = "Turns a half-life into a no-life",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://89873292204381",

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -5),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
