return {
	Name = "Super Shotgun",
	Category = "Gun",
	Weight = "Moderate",
	Price = 45000,
	Level = 55,
	Lore = "A double-barreled shotgun that delivers devastating close-range firepower",
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://106140057291754",

	PreviewCameraOffset = Vector3.new(0, 0, -2),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
