return {
	Name = "Tommy Gun",
	Category = "Gun",
	Weight = "Moderate",
	Price = 55000,
	Level = 55,
	Lore = "Somehow has an infinite clip inside of it. Scientists hate him!",
	SpecialText = "Infinite clip. Please stop suing us.",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://119976864141457",

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -4),

	ItemInfo = {
		DamageType = "Bullet",
	},

	Pills = {
		{ Text = "INFINITE", Color = Color3.new(1, 1, 0) },
	},
}
