return {
	Name = "Unmaykr",
	Category = "Gun",
	Weight = "Heavy",
	Price = 5000000,
	Level = 70,
	Lore = "The ultimate weapon of mass destruction. Capable of obliterating entire armies with a single shot.",
	SpecialText = "Consecutive explosives rounds. Diabolical. And illegal.",
	GroupUnlocked = true,
	Consumable = false,
	GamepassId = 0,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://87033892907244",

	PreviewCameraOffset = Vector3.new(0, 0, -6),

	ItemInfo = {
		DamageType = "Special",
	},

	Pills = {},
}
