return {
	Name = "Candy Cane",
	Category = "Melee",
	Weight = "Light",
	Price = 1000,
	Level = 30,
	Lore = "Originally only available during christmas. We have too many now.",
	SpecialText = "",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://104715404973905",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -2),

	ItemInfo = {},

	Pills = {
		{ Text = "HOLIDAY", Color = Color3.new(0, 1, 0) },
	},
}
