return {
	Name = "Chainsaw",
	Category = "Melee",
	Weight = "Heavy",
	Price = 5000000,
	Level = 70,
	Lore = "Destroys everything it touches. Thats it.",
	SpecialText = "Instant death for most corporeal beings",
	GroupUnlocked = false,
	Consumable = false,
	GamepassId = 0,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://134253995943522",

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0.5, -4),

	ItemInfo = {},

	Pills = {
		{ Text = "INSTANT DEATH", Color = Color3.new(1, 0, 0) },
	},
}
