return {
	Name = "Crucifix",
	Category = "Melee",
	Weight = "Light",
	Price = 90000,
	Level = 70,
	Lore = "Grants total and complete immunity to all damage.",
	SpecialText = "Causes temporary immortality when used",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://78912662651936",

	ItemInfo = {},

	Pills = {
		{ Text = "IMMORTALITY", Color = Color3.new(1, 1, 0) },
	},
}
