return {
	Name = "Crucible",
	Category = "Melee",
	Weight = "Heavy",
	Price = 9000,
	Level = 40,
	Lore = "Decent heavy-hitter for cutting down enemies. WITH DOOOOOM",
	SpecialText = "",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://80757631547671",

	PreviewModelOrientationOffset = Vector3.new(1, 0, 0),
	PreviewCameraOffset = Vector3.new(0, 1, -5),

	ItemInfo = {},

	Pills = {},
}
