return {
	Name = "Festive Airstriker",
	Category = "Melee",
	Weight = "Light",
	Price = 0,
	Level = 0,
	Lore = "Received from defeating Santa Clause. You monster.",
	SpecialText = "Causes a festive bombing run directed at nearest enemy with a cooldown",
	GroupUnlocked = false,
	Consumable = false,
	BadgeTag = "Santa",
	PreviewImage = "rbxassetid://123859830791791",

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -2.5),

	ItemInfo = {},

	Pills = {
		{ Text = "HOLIDAY", Color = Color3.new(0, 1, 0) },
	},
}
