return {
	Name = "Frying Pan",
	Category = "Melee",
	Weight = "Light",
	Price = 12000,
	Level = 25,
	Lore = "Known to cause critical knee-cap pain",
	SpecialText = "Random critical hits. Cannot be dodged.",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://111506760304417",

	PreviewCameraOffset = Vector3.new(0, 0, -2),

	ItemInfo = {},

	Pills = {
		{ Text = "CRITICALS", Color = Color3.new(1, 1, 0) },
		{ Text = "NEVER MISS", Color = Color3.new(0, 1, 1) },
	},
}
