return {
	Name = "Knife",
	Category = "Melee",
	Weight = "Light",
	Price = 55000,
	Level = 35,
	Lore = "Involved in several Murder Mysteries. Causes mild back pain when used improperly.",
	SpecialText = "Backstabs enemies for lethal damage",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://100608703648243",

	PreviewCameraOffset = Vector3.new(0, 0, -2),

	ItemInfo = {},

	Pills = {
		{ Text = "Backstabs", Color = Color3.new(1, 0, 0) },
	},
}
