return {
	Name = "Light Saber",
	Category = "Melee",
	Weight = "Moderate",
	Price = 10000,
	Level = 25,
	Lore = "Recovered from a copyright lawyer",
	SpecialText = "Can fling enemiees on hit (thats the force, probably)",
	GroupUnlocked = false,
	Consumable = false,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://109028960349090",

	PreviewCameraOffset = Vector3.new(0, 1.5, -5),

	ItemInfo = {},

	Pills = {
		{ Text = "THE FORCE (PROBABLY)", Color = Color3.new(0, 1, 1) },
	},
}
