return {
	Name = "Linked Sword",
	Category = "Melee",
	Weight = "Moderate",
	Price = 23000,
	Level = 35,
	Lore = "The classic roblox weapon! Ideal for brick battlers",
	SpecialText = "Use special to lunge. Hold inspect to block.",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://118066147036562",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -3),

	ItemInfo = {},

	Pills = {
		{ Text = "BLOCKING", Color = Color3.new(0.266667, 0, 1) },
	},
}
