return {
	Name = "Mace",
	Category = "Melee",
	Weight = "Moderate",
	Price = 2000,
	Level = 5,
	Lore = "Basic heavy hitter. It was my personal choice back-in-the-day.",
	SpecialText = "",
	GroupUnlocked = true,
	Consumable = false,
	PreviewImage = "rbxassetid://127691296896606",

	PreviewCameraOffset = Vector3.new(0, 1, -4),

	ItemInfo = {},

	Pills = {
		{ Text = "KNOCKBACK", Color = Color3.new(1, 0.6, 0) },
	},
}
