return {
	Name = "Pole Axe",
	Category = "Melee",
	Weight = "Heavy",
	Price = 12000,
	Level = 15,
	Lore = "A long range axe used for hitting enemies in long range. Duh.",
	SpecialText = "",
	GroupUnlocked = false,
	Consumable = false,
	PreviewImage = "rbxassetid://79832300923050",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 0),
	PreviewCameraOffset = Vector3.new(0, 0.5, -6.5),
	ItemInfo = {},

	Pills = {},
}
