return {
	Name = "Shovel",
	Category = "Melee",
	Weight = "Moderate",
	Price = 0,
	Level = 0,
	Lore = "For a guy who needs his petition signed!",
	SpecialText = "Press special for heavy swings. Press inspect to equip petition. Instant kills city congress members.",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://118708879873390",

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -5),

	ItemInfo = {},

	Pills = {
		{ Text = "CRITICALS", Color = Color3.new(1, 1, 0) },
		{ Text = "SOCIAL CHANGE", Color = Color3.new(0, 1, 0) },
	},
}
