return {
	Name = "Skeleton Summoner",
	Category = "Melee",
	Weight = "Heavy",
	Price = 0,
	Level = 0,
	Lore = "Stolen from a local necromancer. Surprisingly chill about it!",
	SpecialText = "Press special or kill NPCs to summon friendly skeletons. Skeletons can get kills for you.",
	GroupUnlocked = false,
	Consumable = false,
	GamepassId = 0,
	BadgeTag = "Candy",
	PreviewImage = "rbxassetid://95631036892602",

	PreviewModelOrientationOffset = Vector3.new(1, 0, 0),
	PreviewCameraOffset = Vector3.new(0, 0, -6),
	IsTorsoDominant = true,
	ItemInfo = {},

	Pills = {
		{ Text = "SPOOKY", Color = Color3.new(1, 0.45, 0) },
		{ Text = "MAGICAL", Color = Color3.new(0.8, 0, 0.6) },
		{ Text = "DARK ENERGY", Color = Color3.new(0.3, 0, 0.6) },
	},
}
