return {
	Name = "Sledgehammer",
	Category = "Melee",
	Weight = "Heavy",
	Price = 0,
	Level = 0,
	Lore = "Favorite toy of Bob, the rock. Great with combos.",
	SpecialText = "Press special to jump-slam the ground. More air time = more damage on land.",
	GroupUnlocked = false,
	Consumable = false,
	BadgeTag = "Bob",
	PreviewImage = "rbxassetid://124741111144977",

	ItemInfo = {},

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -3),

	Pills = {
		{ Text = "LAUNCHES", Color = Color3.new(1, 0, 0) },
		{ Text = "CRITICALS", Color = Color3.new(1, 1, 0) },
	},
}
