return {
	Name = "Susie's Axe",
	Category = "Melee",
	Weight = "Heavy",
	Price = 0,
	Level = 0,
	Lore = "Stolen from a strange purple dinosaur. They were a pretty RUDE BUSTER.",
	SpecialText = "Time your swings for more damage and TP. Press special to use RUDE BUSTER.",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://138179867180533",

	ItemInfo = {},

	-- PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -3),

	Pills = {
		{ Text = "RUDE ENERGY", Color = Color3.new(1, 0, 0.831373) },
		{ Text = "TIMING BONUS", Color = Color3.new(1, 1, 0) },
		{ Text = "SLOWS", Color = Color3.new(0.439216, 0.439216, 0.435294) },
	},
}
