return {
	Name = "Throwing Axe",
	Category = "Melee",
	Weight = "Light",
	Price = 5000,
	Level = 30,
	Lore = "Great for trickshot compilations. Do not juggle.",
	SpecialText = "Hold down attack to charge a throw.",
	GroupUnlocked = false,
	Consumable = false,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://138281262914512",

	PreviewModelOrientationOffset = Vector3.new(1, 0, 0),
	PreviewCameraOffset = Vector3.new(0, 0, -1.5),

	ItemInfo = {},

	Pills = {},
}
