return {
	Name = "Training Sword",
	Category = "Melee",
	Weight = "Moderate",
	Price = 1500,
	Level = 5,
	Lore = "Was the original sword before the linked stole its place!",
	SpecialText = "",
	GroupUnlocked = false,
	Consumable = false,
	IsTorsoDominant = true,
	PreviewImage = "rbxassetid://116352771754481",

	PreviewCameraOffset = Vector3.new(0, 1.5, -4),

	ItemInfo = {},

	Pills = {
		{ Text = "NEVER MISS", Color = Color3.new(0, 1, 1) },
	},
}
