return {
	Name = "Trout",
	Category = "Melee",
	Weight = "Light",
	Price = 0,
	Level = 0,
	Lore = "FISH",
	SpecialText = "Press special to eat. Grants immortality and growing speed boost. Murder to prolong.",
	GroupUnlocked = false,
	Consumable = false,
	BadgeTag = "Fish",
	PreviewImage = "rbxassetid://90986839276291",

	ItemInfo = {},

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -1),

	Pills = {
		{ Text = "NEVER MISS", Color = Color3.new(0, 1, 1) },
		{ Text = "CRITICALS", Color = Color3.new(1, 1, 0) },
		{ Text = "SPEED", Color = Color3.new(1, 1, 1) },
	},
}
