return {
	Name = "Wooden Bat",
	Category = "Melee",
	Weight = "Moderate",
	Price = 100,
	Level = 0,
	Lore = "Classic baseball instrument. With signs of use.",
	SpecialText = "Critical hit on when hitting heads. Jump and attack to swing downwards.",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://132349805600110",

	PreviewModelOrientationOffset = Vector3.new(0, 0, 1),
	PreviewCameraOffset = Vector3.new(0, 0, -4),

	ItemInfo = {},

	Pills = {
		{ Text = "CRITICALS", Color = Color3.new(1, 1, 0) },
	},
}
