return {
	Name = "Hyperlaser Gun",
	Category = "Gun",
	Weight = "Light",
	Price = 5000,
	Level = 20,
	Lore = "Found under a UFO. Scientists believe this is the future of weaponry. Others are eating toasters.",
	SpecialText = "Vaporizes on kill",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://87310765672717",

	ItemInfo = {
		DamageType = "Special",
	},

	Pills = {
		{ Text = "Group", Color = Color3.new(1, 0, 0.0156863) },
		{ Text = "Vaporizes", Color = Color3.new(0, 0.682353, 1) },
	},
}
