return {
	Name = "Knife",
	Category = "Melee",
	Weight = "Light",
	Price = 1500,
	Level = 30,
	Lore = "Involved in several Murder Mysteries. Causes mild back pain when used improperly.",
	SpecialText = "Backstabs enemies for lethal damage",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://101249369458722",

	ItemInfo = {},

	Pills = {
		{ Text = "Backstabs", Color = Color3.new(1, 0, 0) },
	},
}
