return {
	Name = "Machete",
	Category = "Melee",
	Weight = "Moderate",
	Price = 700,
	Level = 2,
	Lore = 'Seller reports "Great in forests ", but common insight suggests its actually terrible',
	SpecialText = "Kills plant-like NPCs more efficiently",
	GroupUnlocked = false,
	Consumable = false,

	PreviewImage = "rbxassetid://102316729615704",

	ItemInfo = {},

	Pills = {
		{ Text = "Anti-Plant", Color = Color3.new(0.160784, 0.694118, 0) },
	},
}
