return {
	Name = "Vest",
	Category = "Armor",
	Weight = "Moderate",
	Price = 10000,
	Level = 35,
	Lore = "Provides basic-level damage protection and occasionally diseases",
	SpecialText = "",
	GroupUnlocked = false,
	Consumable = true,
	MaxStack = 1,

	PreviewImage = "rbxassetid://130394544327723",

	ItemInfo = {
		BulletResistance = 0.2,
		SharpResistance = 0.1,
		BluntResistance = 0.1,
		ArmorType = "Vest",
	},

	Pills = {},
}
