return {
	Title = "Running On Dead Time",
	Artist = "mezz",
	Stems = {
		Leads = {
			Volume = 0.5,
			SoundId = "rbxassetid://71268999017779",
		},
		Percussion = {
			Volume = 0.5,
			SoundId = "rbxassetid://120005542861731",
		},
		Chords = {
			Volume = 0.5,
			SoundId = "rbxassetid://139416169661637",
		},
		Bassline = {
			Volume = 0.5,
			SoundId = "rbxassetid://121921031974365",
		},
		Backing = {
			Volume = 0.5,
			SoundId = "rbxassetid://72517658748653",
		},
	},
	StartingBPM = 170,
	StartingBeatsPerMeasure = 4,
	IntendedPlaybackSpeed = 1,
}
